name: amm-agno
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.12
  - pip
  
  # Core dependencies
  - numpy>=2.2.3
  - pandas>=2.2.3
  - pyarrow>=19.0.1
  - sqlalchemy>=2.0.40
  - pydantic>=2.11.3
  - pydantic-settings>=2.8.1
  - python-dotenv>=1.1.0
  
  # Web and API
  - fastapi>=0.115.12
  - uvicorn>=0.34.2
  - httpx>=0.28.1
  - requests>=2.32.3
  - aiohttp>=3.11.16
  - starlette>=0.46.1
  
  # Database and Vector Store
  - lancedb>=0.22.0
  - pgvector>=0.4.0
  - asyncpg>=0.30.0
  - redis>=5.0.0
  
  # Machine Learning
  - pytorch>=2.6.0
  - torchvision
  - torchaudio
  - transformers>=4.49.0
  - sentence-transformers>=3.4.1
  - scikit-learn>=1.6.1
  - scipy>=1.15.2
  
  # Google AI
  - google-generativeai>=0.8.5
  - google-api-core>=2.25.0
  - google-auth>=2.40.1
  
  # Development tools
  - pytest>=8.3.5
  - pytest-cov
  - pytest-asyncio>=0.26.0
  - pre-commit
  - black
  - isort
  - mypy
  - flake8
  - pylint>=3.3.4
  - jupyter
  - ipykernel
  - ipython
  
  # Additional utilities
  - tqdm>=4.67.1
  - rich>=13.9.4
  - pyyaml>=6.0.2
  - orjson>=3.10.16
  - tenacity>=8.5.0
  
  # CLI tools
  - typer>=0.15.2
  - click>=8.1.8
  
  # Required for some dependencies
  - cuda-version=12.1
  - cudatoolkit=12.1
  - cudnn=8.9
  - nccl>=2.21.5
  - nvtx>=0.2.6
  - numba>=0.59.0
  - numexpr>=2.10.2
  
  # Install remaining packages via pip
  - pip:
    - langchain==0.3.23
    - langchain-community==0.3.21
    - langchain-core==0.3.52
    - langchain-text-splitters==0.3.8
    - langsmith==0.3.31
    - openai==1.77.0
    - openai-agents==0.0.11
    - anthropic==0.50.0
    - fastapi-mcp==0.2.0
    - fastmcp==2.2.0
    - mcp==1.6.0
    - mcp-use==1.2.5
    - streamlit==1.45.1
    - pydeck==0.9.1
    - pydoll-python==1.7.0
    - propcache==0.3.1
    - duckduckgo-search==8.0.0
    - huggingface-hub==0.29.2
    - safetensors==0.5.3
    - tokenizers==0.21.0
    - triton==3.2.0
    - zstandard==0.23.0
